version: '3.8'

services:
  dev-db:
    image: postgres:17-alpine
    container_name: dev-postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: croffers_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  dev_postgres_data: